title: Get openSUSE
title_short: Get
description: Learn about the openSUSE distributions and download them for free
email: admin@opensuse.org
copyright: © 2024 openSUSE contributors
baseurl: ""
url: https://get.opensuse.org
github_url: https://github.com/openSUSE/get-o-o
weblate_url: https://l10n.opensuse.org/projects/get-o-o/
piwik_site_id: 64

navbar_links:
  -
    link: leap/
    text: Leap
  -
    link: tumbleweed/
    text: Tumbleweed
  -
    link: leapmicro/
    text: Leap Micro
  -
    link: microos/
    text: MicroOS
  - locales

footer_links:
  -
    text: source_code
    link: https://github.com/openSUSE/get-o-o
  -
    text: license
    link: https://raw.githubusercontent.com/openSUSE/get-o-o/main/LICENSE

# Only edit below if you know what you are doing!

defaults:
  -
    scope:
      path: "*.html"
    values:
      layout: "default"
  -
    scope:
      path: "*.md"
    values:
      layout: "markdown"
  -
    scope:
      path: "*.markdown"
    values:
      layout: "markdown"

navbar_class: navbar-expand-md sticky-top

plugins:
  - jekyll-redirect-from
  - jekyll-locale
theme: jekyll-theme-opensuse
markdown: kramdown

localization:
  mode       : auto
  locale     : en
  locales_set:
    ar:
      name: العربية
    bg:
      name: Български
    ca:
      name: Català
    cs:
      name: Čeština
    da:
      name: Dansk
    de:
      name: Deutsch
    el:
      name: Ελληνικά
    en:
      name: English
    es:
      name: Español
    es_419:
      name: Español latinoamericano
    et:
      name: Eesti
    fa:
      name: فارسی
    fi:
      name: Suomi
    fr:
      name: Français
    gl:
      name: Galego
    hi:
      name: हिन्दी
    hu:
      name: Magyar
    id:
      name: Indonesia
    is:
      name: Íslenska
    it:
      name: Italiano
    ja:
      name: 日本語
    kab:
      name: Kabyle
    km:
      name: ខ្មែរ
    ko:
      name: 한국어
    lt:
      name: Lietuvių
    nb:
      name: Norsk bokmål
    nl:
      name: Nederlands
    nn:
      name: Norwegian nynorsk
    pl:
      name: Polski
    pt:
      name: Português
    pt_BR:
      name: Português
    pt_PT:
      name: Português europeu
    ro:
      name: Română
    ru:
      name: Русский
    sk:
      name: Slovenčina
    sv:
      name: Svenska
    tr:
      name: Türkçe
    vi:
      name: Tiếng Việt
    th:
      name: ไทย
    tzm:
      name: Central atlas tamazight
    uk:
      name: Українська
    wa:
      name: Walloon
    zh-CN:
      name: 简体中文
    zh_CN:
      name: 简体中文
    zh_HK:
      name: 繁體中文
    zh-TW:
      name: 繁體中文
    zh_TW:
      name: 繁體中文

exclude: [README.md, LICENSE, Gemfile, Gemfile.lock, vendor, Rakefile]
