source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-theme-opensuse', :git => 'https://github.com/opensuse/jekyll-theme.git'
gem 'faraday'
gem 'faraday_middleware'
gem 'human_size'
gem 'jekyll-redirect-from'
gem 'rake'
